version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgul-server
    expose:
      - "8080"                # nginx와 내부 통신용 포트
    # environment:
      # - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net
    env_file:
      - .env

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"      # 외부 → nginx
      - "443:443"  # SSL 붙일 계획 있으면 나중에 사용
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # certbot 인증서 공유 볼륨
      - ./certbot/certbot-etc:/etc/letsencrypt
      - ./certbot/certbot-var:/var/lib/letsencrypt
      # 인증서 검증용 웹 루트 (HTTP-01)
      - ./certbot/certbot-webroot:/var/www/certbot
    depends_on:
      - app
    networks:
      - app-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/certbot-etc:/etc/letsencrypt
      - ./certbot/certbot-var:/var/lib/letsencrypt
      - ./certbot/certbot-webroot:/var/www/certbot

networks:
  app-net:
    driver: bridge
