version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgul-server
    expose:
      - "8080"                # nginx와 내부 통신용 포트
    # environment:
      # - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-net

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"      # 외부 → nginx
      # - "443:443"  # SSL 붙일 계획 있으면 나중에 사용
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # SSL 적용 시 cert/key 볼륨도 추가 가능
    depends_on:
      - app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
